# Geometric Multigrid for 1D Poisson
 
Poisson Equation:

\begin{align*}
\Delta u &= f, & \Omega \\
u &= 0, & \partial \Omega
\end{align*}

Discretizing with finite differences on a regular 1D mesh:

\begin{align*}
&\frac{-u_{i-1} + 2u_i - u_{i+1}}{h^2} = f_i, & i = 1,2,..., N-1 \\
&u_0 = u_N = 0
\end{align*}

Resulting matrix system:

\begin{align}
\frac{1}{h^2}\begin{bmatrix}
2 & -1 & & & & & & \\
-1 & 2 & -1 & & & & & \\
& -1 & 2 & - 1 & & & & \\
&  & \ddots & \ddots & \ddots & & & \\
& & & & & & & \\
& & & & & -1 & 2 & -1 \\
& & & & & & -1 & 2 \\
\end{bmatrix}
\begin{bmatrix}
u_1 \\
u_2 \\
\\
\vdots \\
\\
\\
u_{N-1} \\
\end{bmatrix}
=
\begin{bmatrix}
f_1 \\
f_2 \\
\\
\vdots \\
\\
\\
f_{N-1} \\
\end{bmatrix}
\end{align}

In [21]:
# Import some python libraries we need
import numpy as np
import matplotlib.pyplot as plt

# Size of the fine-grid problem
N = 16
N_c = int(N/2)

# 1D Model problem
A = np.diag(2*np.ones(N-1)) + np.diag(-1*np.ones(N-2),k=-1) + np.diag(-1*np.ones(N-2),k=1) 
A_c = 0.25*np.diag(2*np.ones(N_c-1)) + np.diag(-1*np.ones(N_c-2),k=-1) + np.diag(-1*np.ones(N_c-2),k=1) 

# Print the matrix
# print(A)

# Define a random solution and corresponding right-hand side
u_final = np.random.rand(N-1)
f = np.dot(A,u_final)
u = np.zeros((N-1,))

# Define a constant right-hand side and corresponding solution
# f = np.ones(N-1)
# u_final = np.linalg.solve(A,f)
# u = np.zeros(N-1)

# Define a zero right-hand side and random initial guess
# f = np.zeros(N-1)
# u_final = np.zeros(N-1)
# u = -1 + 2*np.random.rand(N)
# u = np.cos(np.arange(N)*np.pi)

# Initialize iteration count and next iterate
u_next = u.copy()
i = 0

In [22]:
# Linear interpolation
P = np.zeros((N-1,N_c-1))
P[0,0] = 0.5
P[N-2,N_c-2] = 0.5
for i in range(2,N-1):
    if i % 2 == 0:
        P[i-1,int((i-1)/2)] = 1
    else:
        P[i-1,int((i-2)/2)] = 0.5
        P[i-1,int((i)/2)] = 0.5
# print(P)

In [23]:
# Restriction by injection
N_c = int(N/2)
R_I = np.zeros((N_c-1,N-1))
for i in range(N_c-1):
    R_I[i,2*i+1] = 1
# print(R_I)

In [32]:
# Restriction by full-weighting
R_FW = 0.5*P.transpose()
# print(R_FW)

In [33]:
print(A_c)
print(np.dot(R_FW, np.dot(A,P)))

[[ 2. -1.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0. -1.  2.]]
[[ 0.5  -0.25  0.    0.    0.    0.    0.  ]
 [-0.25  0.5  -0.25  0.    0.    0.    0.  ]
 [ 0.   -0.25  0.5  -0.25  0.    0.    0.  ]
 [ 0.    0.   -0.25  0.5  -0.25  0.    0.  ]
 [ 0.    0.    0.   -0.25  0.5  -0.25  0.  ]
 [ 0.    0.    0.    0.   -0.25  0.5  -0.25]
 [ 0.    0.    0.    0.    0.   -0.25  0.5 ]]
